# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8786f34746371e6858ac271e6b40f52ac0277d693698251de05f8dbb6383d196566805a863e8a87a945d192fda11b9c3757dadd5ac6493e281c3e79f88d73b59

test:
  secret_key_base: fc34e95a6ccc12e793fcd84e182dcd159fde0ec0463153fc0b1a1e43dc12fb32236d0e01309e4a0153a582eaca3f564d07a4e926cdef4b09a51418ca3fcf0868

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
